//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment
    {
        public int Id { get; set; }
        public Nullable<int> Idstudent { get; set; }
        public Nullable<int> Iditems { get; set; }
        public Nullable<int> assessment1 { get; set; }
    }
}
